language: php
cache:
  directories:
    - $HOME/.composer/cache/files
php:
  - 7.2
  - 7.3
  - 7.4
  - nightly
before_script:
  - composer install --prefer-dist
script:
  - ./vendor/bin/phpunit tests/
